Wayland startup and bug fixes.

diff --git a/usr/bin/archlinux-kernel-manager b/usr/bin/archlinux-kernel-manager
--- a/usr/bin/archlinux-kernel-manager
+++ b/usr/bin/archlinux-kernel-manager
@@ -4,69 +4,90 @@
 # the polkit agent running on the desktop environment should prompt for root password
 
 echo "---------------------------------------------------------------------------"
-echo "[INFO] Checking session"
-test $(whoami) == "root" && echo "[ERROR] Do not run this script as root." && exit 1
-test -z $DISPLAY && echo "[ERROR] DISPLAY variable is not set." && exit 1
+echo "[INFO]: Checking session"
+test $(whoami) == "root" && echo "[ERROR]: Do not run this script as root." && exit 1
+test -z $DISPLAY && echo "[ERROR]: DISPLAY variable is not set." && exit 1
 
 # check session is either one of X11, Wayland or TTY
-session=$(loginctl show-session $(loginctl|grep $(whoami) | awk '{print $1}') -p Type | awk -F= '{print $2}' | grep "x11\|wayland\|tty")
+SESSION=$(loginctl show-session $(loginctl|grep $(whoami) | awk '{print $1}') -p Type | awk -F= '{print $2}' | grep "x11\|wayland\|tty")
+test -z "$SESSION" && echo "[ERROR]: Failed to verify session for user, SESSION = $SESSION" && exit 1
 
-test -z "$session" && echo "[ERROR] Failed to verify session for user." && exit 1
+XAUTHORITY=$(xauth info | awk -F"Authority file:" '{print $2}' | tr -d ' ')
+test -z "$XAUTHORITY" && echo "[ERROR]: XAUTHORIY file is not set" && exit 1
+test -s "$XAUTHORITY" || touch "$XAUTHORITY"
 
-xauth_file=$(xauth info | awk -F"Authority file:" '{print $2}' | tr -d ' ')
-test -s "$xauth_file" || touch "$xauth_file"
+XAUTH_HONORED=$(xauth info | awk -F"Changes honored:" '{print $2}' | tr -d ' ')
+test $XAUTH_HONORED = "yes" || echo "[ERROR]: Xauth changes honored = no, restart X server" || exit 1
 
-# GDK_BACKEND=x11 - force GTK to use XWAYLAND
 # GTK_A11Y=none - fixes the dbus-launch errors with GTK4
 
-function start_on_wayland() {
+echo "[INFO]: XAUTHORITY = $XAUTHORITY"
+echo "[INFO]: DBUS_SESSION_BUS_ADDRESS = $DBUS_SESSION_BUS_ADDRESS"
+echo "[INFO]: DESKTOP SESSION = $DESKTOP_SESSION"
+
+function start_in_wayland() {
+  echo "[INFO]: Starting in Wayland session"
   xauth gen $DISPLAY &> /dev/null
-  test -z "$(xauth list)" || echo "[INFO] Xauth session = OK"
-  pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS GTK_A11Y=none GDK_BACKEND=x11 '/usr/share/archlinux-kernel-manager/archlinux-kernel-manager.py'
+
+  case "$DESKTOP_SESSION" in
+    plasma | gnome)
+        pkexec env DISPLAY=$DISPLAY WAYLAND_DISPLAY="$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" XAUTHORITY=$XAUTHORITY DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS GDK_BACKEND=x11 GTK_A11Y=none '/usr/share/archlinux-kernel-manager/archlinux-kernel-manager.py'
+    ;;
+    *)
+      pkexec env DISPLAY=$DISPLAY WAYLAND_DISPLAY="$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" XAUTHORITY=$XAUTHORITY DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS GTK_A11Y=none '/usr/share/archlinux-kernel-manager/archlinux-kernel-manager.py'
+    ;;
+  esac
 }
 
-function start_on_x11() {
-  test -z "$(xauth list)" || echo "[INFO] Xauth session = OK"
+function start_in_x11() {
+  echo "[INFO]: Starting in X11 session"
   pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS GTK_A11Y=none '/usr/share/archlinux-kernel-manager/archlinux-kernel-manager.py'
 }
 
-case "$session" in
+function start_in_tty() {
+  echo "[INFO]: Starting in TTY session"
+  pkexec '/usr/share/archlinux-kernel-manager/archlinux-kernel-manager.py'
+}
+
+case "$SESSION" in
     "wayland")
       # Wayland session, generate Xauth session cookie for $DISPLAY
-      start_on_wayland
+      echo "[INFO]: Display = $DISPLAY"
+      echo "[INFO]: Session = $SESSION"
+      start_in_wayland
     ;;
     "x11")
       # X11 session, don't do anything here
-      echo "[INFO] Display = $DISPLAY"
-      echo "[INFO] Session = $session"
+      echo "[INFO]: Display = $DISPLAY"
+      echo "[INFO]: Session = $SESSION"
 
       # just show msg on whether the Xauth session cookie is setup
-      start_on_x11
+      start_in_x11
     ;;
     "tty")
       # TTY session, as user may not use a display manager
-      echo "[INFO] Display = $DISPLAY"
-      echo "[INFO] Session = $session"
+      echo "[INFO]: Display = $DISPLAY"
+      echo "[INFO]: Session = $SESSION"
 
-      start_on_x11
+      start_in_tty
     ;;
     *)
       # anything here is an unknown session, most likely AKM will fail to load
-      echo "[INFO] Display = $DISPLAY"
-      echo "[INFO] Session could not be verified ... falling back to use XDG_SESSION_TYPE"
+      echo "[INFO]: Display = $DISPLAY"
+      echo "[INFO]: Session could not be verified ... falling back to use XDG_SESSION_TYPE"
 
       case "$XDG_SESSION_TYPE" in
         "wayland")
-          start_on_wayland
+          start_in_wayland
         ;;
         "tty")
-          start_on_tty
+          start_in_tty
         ;;
         "x11")
-          start_on_x11
+          start_in_x11
         ;;
         *)
-          echo "[ERROR] $XDG_SESSION_TYPE is empty, cannot continue"
+          echo "[ERROR]: $XDG_SESSION_TYPE is empty, cannot continue"
           exit 1
         ;;
       esac
